### ISSUE TITLE
Testing for end-to-end sync

### ISSUE THREAD

**Issue by jjtswan** [google/fhir-app-examples#18]

**Comment by jjtswan** [comment]
Assigning to Fred while waiting to add Anchita to this repository.

**Comment by jjtswan** [comment]
TODO: Assign to Anchita after we've added her to the repository.

**Comment by anchita-g** [comment]
Completed stability testing of E2E sync by following the [instructions](https://github.com/google/fhir-app-examples#readme) to setup the different components.
As a part of stability testing, we were able to try out various sync strategies to sync resources by modifying the demo app in this repo.
Following issues have been identified as a part of trying out the different sync strategies in the various components. Few of these issues have already been filed as well.
Issues identified in the [Android FHIR SDK](https://github.com/google/android-fhir):
1) Adding support for issuing `Bundle` requests to the resource server in the `DownloadWorkManager`
2) Facing [exception](https://paste.googleplex.com/5108902701039616): `org.fhir.ucum.UcumException` while saving [`Observation` ](https://paste.googleplex.com/4506333586915328)resources emitted as a part of the implementation of `DownloadWorkManager`. 

Issues identified in the [FHIR Gateway](https://github.com/google/fhir-gateway):
1) Support to fetch a batch of `Patient` resources by querying the patient IDs: This issue has already been identified and filed [here](https://github.com/google/fhir-gateway/issues/45).
2) As of now `AllowedQueriesChecker` only works to allow queries based on the HTTP Request URL path and query parameters. We should also support the same for `Bundle` type of requests, where each entry in the `Bundle` is a different request

**Comment by anchita-g** [comment]
With the above issues being identified, we can carry out performance benchmarking on the various components as next steps. We should create another issue to track those efforts.
